### ISSUE TITLE
A question about data acquisition rate of pymodaq.

### ISSUE THREAD

**Issue by rickwubulabudabuda** [PyMoDAQ/PyMoDAQ#119]
Hi！
I have a question about the maximum data acquisition rate that pymodaq can support. Can it support the data acquisition rate of GHZ?
Hope to get your reply soon. 
Thanks a lot!

**Comment by quantumm** [comment]
Hi,
For sure pmd cannot support a data acquisition rate of gigahertz. Nothing that use a computer can do that. If you need such speed you should go for an analogic solution, like an oscilloscope.
