### ISSUE TITLE
Dashboard fails to recognize plugin

### ISSUE THREAD

**Issue by NanjeofKro** [PyMoDAQ/PyMoDAQ#140]
I'm not sure whether a GitHub issue is the right way to bring it up, as I doubt it's an issue with PyMoDAQ as such, but I don't really know where else to turn. I am currently trying to develop a pymodaq plugin to allow for reading from and controlling Bronkhorst MFCs; however, I cannot try the plugin out because I can't seem to make PyMoDAQ recognize the plugin's existance. I've used the plugin template as the basis for my plugin to ensure proper syntax and named it "pymodaq_plugins_bronkhorst", which are the requirements listed at http://pymodaq.cnrs.fr, but it does not seem to work. I've also tried forking pymodaq_plugin_manager and adding the plugin to PluginList.json without any luck (although I did not know what to put in the "id" field for the new entry). Is there something else code-wise that I am missing to make PyMoDAQ recognize the plugin? My code so far is available here: https://github.com/NanjeofKro/pymodaq_plugins_bronkhorst .

Thank you in advance!

**Comment by quantumm** [comment]
Hello,
I do not have so much time right now to look at the detail of your problem, but did you have a look at [this tutorial](https://pymodaq.cnrs.fr/en/latest/tutorials/plugin_development.html)? I may help you for your plugin development.
Good luck!

**Comment by seb5g** [comment]
Very quickly I noticed your plugin class name is not the same ad your module (missing s at the end : DAQ_0DViewer_Bronkhorst_MFC
should be DAQ_0DViewer_Bronkhorst_Mfcs

see the s and the lower case to match your module name (the name of the py file where the class is defined)
