### ISSUE TITLE
Problem of installation on Mac

### ISSUE THREAD

**Issue by JujuGull** [PyMoDAQ/PyMoDAQ#157]
When trying to install pymodaq with the command "pip install pymodaq", I have the following issue:

Found conda env: ``/Users/justine/miniconda3/envs/form_pymodaq``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.

Trying with a 3.8 version of python instead of 3.10 doesn't fix the issue.

**Comment by quantumm** [comment]
Hi,
You can have a look at this recent discussion: https://github.com/PyMoDAQ/PyMoDAQ/issues/153
but notice that PyMoDAQ is not supported for Mac.

**Comment by seb5g** [comment]
this is related to the hdf5 library that's needed by pymodaq and the tables package: https://www.pytables.org/ that needs it. As @quantumm said, we are not supporting on mac even if we know it should work. So you should investigate and reinstall the hdf5 library. Let us now if you find a solution!

**Comment by JujuGull** [comment]
Thank you for your answers!

I have just tried to install tables package but it lead to the same error: 

  1 error generated.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.8.18 (default, Sep 11 2023, 08:17:16)
      * Found cython 3.0.3
      * USE_PKGCONFIG: False
      * Found conda env: ``/Users/justine/miniconda3/envs/form_pymodaq_pyth3_8``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.

I tried to install with different environments and python: 3.8; 3.9; 3.10

If I try to install the version 3.1 of tables (which seems to be the most stable), I have another error: this one:

(form_pymodaq_pyth3_8) justine@hnu-imgacq-e ~ % pip install tables==3.1
Collecting tables==3.1
  Using cached tables-3.1.0.tar.gz (6.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lj/ntz_bb9n43n205zskl5_srjr0000gn/T/pip-install-kd_ozobo/tables_2598df0722b3405c98afa247b3cc5c35/setup.py", line 55, in <module>
          from distutils.command.build_py import build_py_2to3 as build_py
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/Users/justine/miniconda3/envs/form_pymodaq_pyth3_8/lib/python3.8/site-packages/setuptools/_distutils/command/build_py.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

As it is ok on Windows, I will stay with it :)
