### ISSUE TITLE
loss of detectors in daq_scan

### ISSUE THREAD

**Issue by francoisBmallet** [PyMoDAQ/PyMoDAQ#159]
Hi, 
  I am having an issue with data acquisition (and plotting) of multiple detectors. Let's take just 2 0D mocks and one actuator. In daq-scan, It seems like the detector names are not correctly passed when grabbing the data and that the next detector overwrites the previous one. Anyway, impossible to plot both mock detector at the same time.

**Comment by seb5g** [comment]
The new PR #160 solves this issue. Could you test it and close the issue if that's fine? Thanks

**Comment by francoisBmallet** [comment]
Hey thanks, just tested and all good now !
