### ISSUE TITLE
Super call instead of explicit parent class init call

### ISSUE THREAD

**Issue by bmoneke** [PyMoDAQ/PyMoDAQ#172]
Looking at the thread dying issue #168, I found the following code:

https://github.com/PyMoDAQ/PyMoDAQ/blob/30f6f7877bfa8fc140841118288fe188c6077238/src/pymodaq/control_modules/daq_viewer.py#L101-L103

A skmple `super().__init__()` should be enough.

That will call the init of the first parent class.
If that class is well written, it will contain another `super.__init__()` (best with handling all excess kwargs), which will resolve to the second parents init.

That continues until all parents (direct and the parents of parents) have been called.
If any parent class is QObject, that will be initialized as well. 

See also:
- general regarding super https://rhettinger.wordpress.com/2011/05/26/super-considered-super/
- for the method resolution order: https://www.python.org/download/releases/2.3/mro/

**Comment by seb5g** [comment]
Thanks for pointing this out however I'm well aware of that but when using super and multiple inheritance as I do here lead to various issues. At the end I thought it would be easier/clearer to init each parent separately.

**Comment by bmoneke** [comment]
I just tested it, and it worked, but that is obviously not a comprehensive test. I understand your reluctance.

Your current code initializes "QObject" twice, by the way, as ControlModul also initializes "QObject".

**Comment by seb5g** [comment]
For the time being I think we will stick to not use the super method here, but we will move away the second QObject initialization. I did it in https://github.com/PyMoDAQ/PyMoDAQ/commit/862d0ed12d7a591b76c2323c59af855ad480ec87

Thx
