### ISSUE TITLE
Pymodaq4.0.8: No installed detectord on start up

### ISSUE THREAD

**Issue by Ashwolaa** [PyMoDAQ/PyMoDAQ#173]
I get this error trying to launch pymodaq from a fresh install ( uninstall + install)
Python version: 3.9.16
Sytem: Ubuntu 18
I also deleted the whole etc/.pymodaq folder content to start from a fresh config.

Successfully installed pymodaq-4.0.8

**(pymodaq) cs268225@iram-fa-007534:~/Documents/Python/TDC$ dashboard**

Traceback (most recent call last):
  File "/home/cs268225/anaconda3/envs/pymodaq/bin/dashboard", line 5, in <module>
    from pymodaq.dashboard import main
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/dashboard.py", line 32, in <module>
    from pymodaq.control_modules.daq_move import DAQ_Move
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/daq_move.py", line 22, in <module>
    from pymodaq.control_modules.utils import ControlModule
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/utils.py", line 64, in <module>
    raise DetectorError('No installed Detector')
pymodaq.utils.exceptions.DetectorError: No installed Detector

**(pymodaq) cs268225@iram-fa-007534:~/Documents/Python/TDC$ daq_move**

Traceback (most recent call last):
  File "/home/cs268225/anaconda3/envs/pymodaq/bin/daq_move", line 5, in <module>
    from pymodaq.control_modules.daq_move import main
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/daq_move.py", line 22, in <module>
    from pymodaq.control_modules.utils import ControlModule
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/utils.py", line 64, in <module>
    raise DetectorError('No installed Detector')
pymodaq.utils.exceptions.DetectorError: No installed Detector

**(pymodaq) cs268225@iram-fa-007534:~/Documents/Python/TDC$ daq_viewer**
Traceback (most recent call last):
  File "/home/cs268225/anaconda3/envs/pymodaq/bin/daq_viewer", line 5, in <module>
    from pymodaq.control_modules.daq_viewer import main
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/daq_viewer.py", line 24, in <module>
    from pymodaq.control_modules.utils import ControlModule
  File "/home/cs268225/anaconda3/envs/pymodaq/lib/python3.9/site-packages/pymodaq/control_modules/utils.py", line 64, in <module>
    raise DetectorError('No installed Detector')
pymodaq.utils.exceptions.DetectorError: No installed Detector

I believe the problem comes from config_pymodaq.toml on launch, I deleted the file but it does not change the output when the file is created for the first time.

Best,
Constant

**Comment by quantumm** [comment]
Hi,
I had no problem installing with the version 3.8 of python.
OS: Ubuntu 20.04.
Here is my python environment: 
[environment.md](https://github.com/PyMoDAQ/PyMoDAQ/files/13069302/environment.md)

Best,
David

**Comment by seb5g** [comment]
Config files are stored both in /etc/.pymodaq and in ~home/.pymodaq
But I don't think this is related. It just seems you have missing packages! When installing pymodaq, the package: pymodaq_plugins_mock is in the requirements and should installed the mock actuators and detectors. Check this guy is installed correctly (but I never had the issue).
Let us know of your progress

**Comment by quantumm** [comment]
Nice ;)
Actually I also have this problem of access on the folder /etc/.pymodaq I will try the command with chmod.
It should be possible to automate this in a way at the installation i guess.

**Comment by quantumm** [comment]
Before doing the commands recommanded by @Ashwolaa I had this message at running a dashboard: "Cannot create local config folder at this location: /etc/.pymodaq, try using admin rights. Changing the not permitted path to a user one: /home/dbrestea/.pymodaq."

Now it is solved.

Thanks ;)

**Comment by seb5g** [comment]
This is indeed related to ownership of this folder created during the first run of pymodaq. In some cases, this folder is ok for reading/writing, in other cases it is not...

The function handling this is defined in the pymodaq.utils.config module:

```
def get_set_path(a_base_path: Path, dir_name: str) -> Path:
    path_to_get = a_base_path.joinpath(dir_name)
    if not path_to_get.is_dir():
        try:
            path_to_get.mkdir()
        except PermissionError as e:
            print(f"Cannot create local config folder at this location: {path_to_get}"
                  f", try using admin rights. "
                  f"Changing the not permitted path to a user one: {Path.home().joinpath(dir_name)}.")
            path_to_get = Path.home().joinpath(dir_name)
            if not path_to_get.is_dir():
                path_to_get.mkdir()
    return path_to_get
```

This is a poor workaround as the initial goal of this was to have a kind of public folder that all user would use (to store the preset for instance) and one specific to each user. I've read that for linux, it is usually in /etc hence the creation of /etc/.pymodaq . However, in linux, the ownership and rights to read/write is quite tricky... 

In pymodaq postinstall one shoud run a small script to create and change rights on this folder. I already do this in the continuous integration:

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/6517bb1c-7f08-4b0f-86a6-e7756c60548b)

So either, we try to include it in the postinstall of pymodaq (never done it before, but I've read about that a bit) or make a special chapter in the doc for linux install.

I vote for the second option because we could also put some documentation of packages that are needed to run qt properly on linux:

![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/5908f597-16c5-4ee0-8cab-b804806a2f27)

If we go for that, could you write this part of the documentation?

**Comment by Ashwolaa** [comment]
I can do that, I do not know much for now on the packages needed in Linux though (doesn't pip install pyqt5/Pyside6 does it?).

But I can write the procedure I used in the documentation

**Comment by seb5g** [comment]
there is not always all the right packages that are installed depending on which linux you work on... Thanks for adding the procedure in the doc!

**Comment by Ashwolaa** [comment]
Do you have the list of packages needed?

**Comment by seb5g** [comment]
here is the command I run in continuous integration servers:

```
sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
```

**Comment by seb5g** [comment]
Ok PR #180 precise the procedure for linux installation in the documentation. Closing the issue

**Comment by quantumm** [comment]
Actually should not we make a choice about a Linux distribution we support "officially"? That would probably prevent such problem.
I would vote for Ubuntu since it is probably the most common one, and we are already two people in the maintainers to use it ;)

**Comment by seb5g** [comment]
Well, the servers where the continuous integration is done are ubuntu which is the default OS for linux tests. I'm also running tests on windows (and we could also include macos...). So maybe we could just state this: I mean that the tests are run on ubuntu and that for other linux distribution the user should know there will not be any supports...

**Comment by quantumm** [comment]
Yes that sounds reasonable ;)
