### ISSUE TITLE
Send signal of parameter tree settings when initializing detector

### ISSUE THREAD

**Issue by Ashwolaa** [PyMoDAQ/PyMoDAQ#177]
Hi,

I would like to initialize my detector with the Parameter tree settings saved. Is there already a function to loop through all the parameter tree and send their respective values?

Otherwise, I think I will make one.  It could also be given as an input when initializing detector (aka a fixed parameter in comon_parameters)

**Comment by quantumm** [comment]
But cannot you do that with a preset?
I mean that you open a dashboard and define a preset with your detector and the settings you would like. You then just have to load this preset at startup.

**Comment by Ashwolaa** [comment]
I want to find the good parameters, then load them as a preset.
This will update correctly the parameter tree but not necessarily the instrument.
I just wanted to insure that all the parameters I set up in my preset where being sent to the apparel in case someone changed it.

I would like to loop through all the parameters with the commit settings. But I think, I will just use a function in the ini_detector such as 
`[self.commit_settings(p) for p in parameters]`
or maybe make subvariable for the relevant parameters.
`[self.commit_settings(p) for p in relevant_parameters]`

**Comment by quantumm** [comment]
Yes that sounds good ;)

**Comment by Ashwolaa** [comment]
I retrieved a nice function that I found when randomly moving in pymodaq's folders. This seem well adapted to iterate through all children.

'from pymodaq.utils.parameter import utils'
'[self.commit_settings(param) for param in utils.iter_children_params(self.settings)]'
        
with a custom settings, one could add
'from pymodaq.utils.parameter import utils'
'relevant_parameters_name = ['p1','p2',...]'
'[self.commit_settings(param) for param in utils.iter_children_params(self.settings) if param.name() in relevant_parameters_name]'

**Comment by seb5g** [comment]
yes this is the one you should use!

What you want to do is fine if these relevant parameters are simple ones. What I mean is that sometimes, one parameter value would change the values of others parameters (or their options such as visible or enabled), in that case applying values as you propose could lead to various issues. So be careful...

I guess saving/loading params from a local file could be easily enabled either from within the plugin or from the main ui. Another approach would be to load them from a config file that can be tailored for each user on the machine. The only drawback of both methods compared to load from the preset is that it is not automatic and you will have to do it for each control module once init in the dashboard.

Maybe you could do it for your detector as you wish and once you're staisfied (or not) with the usage come back here to comment on it so we can implement it or something else for all control modules!

**Comment by seb5g** [comment]
PR #222 answer this issue, I'm closing it. Thanks @Ashwolaa  for raising this and the work you've done on it also!
