### ISSUE TITLE
Saving the parameter tree settings in the h5 when launching scan/acquisition

### ISSUE THREAD

**Issue by Ashwolaa** [PyMoDAQ/PyMoDAQ#181]
Following the discussion on the saving of meta data, I would like to save the state of my parameter tree settings for my detector when launching a scan or an acquisition (maybe not all of it but still, some choice for the parameters would be welcome). The parameter tree would be saved as metadata in the h5.

This seems a good way to also store the relevant parameters used for each scan, both for reproducibility and comparison.

Is there already a function/class to do that?

**Comment by seb5g** [comment]
Well it is already done actually. When you open a file using the H5Browser, clicking on a node will display its metadata. If there is one called settings in those, it will be rendered just like the settings tree. Each scan node saved the scan settings. Within these scan nodes, you'll find the detectors and actuators node each having their settings saved from the time the scan was done.

**Comment by seb5g** [comment]
It has been discussed in our recent workshop that it could be interesting to also save the settings of the control modules not actually used in a scan but active in the dashboard as they represent the status of an experiment at a given time.

**Comment by Ashwolaa** [comment]
Perfect, that is exactly what I needed!

**Comment by seb5g** [comment]
Alright then I'm closing the issue
