### ISSUE TITLE
no data saved by db_logger

### ISSUE THREAD

**Issue by bernhardlang** [PyMoDAQ/PyMoDAQ#210]
Hi
To play with logging into SQL database I've set up a preset with a single Mock 0D detector. Database is configured, connect works. A database with the name of the preset is created and contains a couple of tables. After pressing the two green "play" buttons, the dashboard displays the incoming data and "N saved" on the log panel counts up (but faster than the data rate, ??). However, the table datas0D, where I would expect the logged data to show up, remains empty.

At the same time, continued messages

ERROR:pymodaq.db_logger:The index should be a positive integer lower than the data length

fill the console window from where the dashboard was started. I guess that sending data to the database is skipped because of that error. There are two locations where this message is issued: utils/data.py:1727 and utils/data.py:1733 which are to be found in the __getitem__ and __setitem__ methods of DataToExport
Any ideas what is going wrong?

**Comment by seb5g** [comment]
yes I do,
The data logging to database has not been refreshed since I moved to the new database layout (as I presented in the pymodaq days). I thought mostly no one was using this feature so it was not my priority. I'll mark your issue

**Comment by bernhardlang** [comment]
Thanks. I thought this feature could be used for a logging system of the "environmental conditions" in the laser lab, temperature, humidity and beam pointing / stabilizers. Typically one wants to browse though some time intervals during which something "interesting" happened. A data base looks to me being more adequate for such task than an ever-growing large file. However, its not on my priority list neither. And it could also be implemented with saving to file, at least for the time being.

**Comment by seb5g** [comment]
Hi Bernard, branch dblogger_pymo4 and PR #219  should be allowing to use again the DAQ_Logger extension using postgresql database. I've checked it on my computer using a local database. Could you also test it and let me know if you still have issues!

**Comment by bernhardlang** [comment]
Looks like my reply didn't make it until here. I've tested it and get the expected result. Thanks!
