### ISSUE TITLE
Indexing of scan while taking negative steps

### ISSUE THREAD

**Issue by Khodeo** [PyMoDAQ/PyMoDAQ#224]
Hi

I don't know if this is of concern, but I noticed that in pymodaq4 while taking the 1D and 2D scans the indexing given by

self.scanner.get_indexes_from_scan_index(self.ind_scan)

in the daq_scan go from 0 to N if the step of the actuator is positive, while go backward from N to 0 if the step of the actuator is negative. In the final h5 file the nav_axis is instead saved always in the correct ordering, as is defined by the user. 

I think this is because in the scan_factory the function get_info_from_positions is using a numpy.unique(ax) that is also sorting ax. If the convention on the indexing going from 0 to N is to be mantained both for positive and negative steps, I think this could be substituted with something like

ax_indexes = np.unique(ax, return_index=True)[1]
ax=[ax[index] for index in sorted(ax_indexes)]
axes_unique.append(np.array(ax)) 

in order to mantain the ordering of the user defined axis while doing the unique.

**Comment by seb5g** [comment]
Indeed in some cases the indexing with respect to the navigation axis is reversed, I'll look at PR230 for this. I guess we need some testing to make sure the indexing is always correct with respect to the saved axes (the nav one especially because set by the scanner)
