### ISSUE TITLE
no data in h5 file from Log data extension 

### ISSUE THREAD

**Issue by bernhardlang** [PyMoDAQ/PyMoDAQ#250]
Hi
Running the "Log data" extension on a newly written plugin I end up with a h5 file which seems not to contain any data. The problem can be reproduced performing a "Log data" on a generic mock plugin. All initializes correctly, data is show during acquisition. However, inspecting the resulting file with the h5browser, only the entry "Logger" contains string data in form of the message that acquisition has started. The entry "Detector000" is empty. Idem when firing up the python shell, importing h5py and inspecting the file manually. Am I missing something? Thanx for help!

**Comment by seb5g** [comment]
Hi @bernhardlang 
You didn't miss anything, there is indeed a bug, I just patched this into PR #251 This should solve your issue. I'll do the PR on both 4.1.x and 4.2.x_dev branch. I will also published a patch release as this is a hotfix! Make sure to test it and close the issue if satisfied

**Comment by bernhardlang** [comment]
Thanks for the quick fix! Tested with mock plugin and my own plugin. Data now stored correctly.

Most probably unrelated, however and FYI: when closing the browser after viewing data from the mock plugin, it crashed. log file attached.
[pymodaq.log](https://github.com/PyMoDAQ/PyMoDAQ/files/14179427/pymodaq.log)

**Comment by seb5g** [comment]
thanks for raising this crash, i fixed the related error with PR #258 but its strange because there was a exception catching that should have prevented the crash...
