### ISSUE TITLE
Pyleco for python 3.8

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/PyMoDAQ#277]
In https://github.com/pymeasure/pyleco/pull/61 I successfully reduced the requirement to Python 3.8 by replacing the dependency by my own code and changing typing.

Python 3.7 failed due to setup tools I have to investigate, whether I can achieve Python 3.7.

Due to the larger changes, I will have to test it, before doing a release.

**Comment by seb5g** [comment]
thanks a lot @BenediktBurger

**Comment by BenediktBurger** [comment]
python 3.7 requires dropping `typing.Protocol`, which I use extensively.
With more effort and pain, we could reduce the requirements to Python 3.7, but I prefer starting at 3.8.

**Comment by seb5g** [comment]
For python 3.8+ you can use https://pypi.org/project/typing-extensions/ if some python versions lacks typing utilities you're using!

Unfortunately they don't do it for python 3.7...

**Comment by BenediktBurger** [comment]
I reorganized some things, such that I could publish a pyleco 0.3 version for python>=3.8.
Would you prefer an earlier release (these days) or don't you care if it comes later?
In the latter case, I can address some small issues as well.

**Comment by seb5g** [comment]
nothing urgent on our side @rgeneaux did'nt come back with use case issues yet ;-)

**Comment by rgeneaux** [comment]
yes we're working on the laser side of things for a while so software questions will come later - take your time Benedikt!

**Comment by BenediktBurger** [comment]
Pyleco 0.3.0 is out with support for Python 3.8.

**Comment by seb5g** [comment]
Awesome I'll be able to include it in the next minor release

**Comment by BenediktBurger** [comment]
I reopened the issue such that it is a reminder to adjust the requirements, when to install pyleco.

**Comment by seb5g** [comment]
I think you can close it as the requirement have been set in the new versions

**Comment by BenediktBurger** [comment]
Included in pymodaq 4.2.
