### ISSUE TITLE
Graphical documentation of inputs

### ISSUE THREAD

**Issue by TheSirC** [PyMoDAQ/PyMoDAQ#29]
The software contain many inputs that have names that do not translate to the full explanation of their use or intent. 

Qt (and pyQt5 by extension) contains a mechanism that can pop up a tooltip on hover ([example here](https://d33wubrfki0l68.cloudfront.net/bcda291e8b6098318b6866b8ae3a03ca2218339b/25bf9/wp-content/uploads/2017/04/qt-tooltip.png.webp)) with the following syntax:

```python
button.setToolTip('<b>Tooltip documentation</b>')
```

This tooltip could further improve the user experience by allowing documentation to come on-the-fly on top of being styleable with HTML-like syntax.

A quick search yielded 175 buttons that could have a tooltip. Obviously documenting each of them could be tedious and time-consuming. It would be possible to re-use some of the documentation as some button share behavior. 

A possible follow-up could be to have a detailed listings of the said 175 buttons (it is is easily available on request). Please confirm the stance on the issue.

**Comment by TheSirC** [comment]
> It would be possible to re-use some of the documentation as some button share behavior.

A programmatic mechanism to inherit documentation could also be created but the complexification of the code seems unreasonable.

**Comment by seb5g** [comment]
Could you point out these missing tooltips?

**Comment by TheSirC** [comment]
Sure. Would you like all of them or just an excerpt ?

**Comment by seb5g** [comment]
Well do you think you would know where to add them and what to put in them? There are basically two possibilities: either on the Qt Designer ui files or in the Parameter dict descriptions (possible to add a **tip** key, value pair. Let me know?

**Comment by TheSirC** [comment]
I will post here if any are a mystery to me

**Comment by seb5g** [comment]
Great! Thanks for the help.
