### ISSUE TITLE
Wrong link Third edition of the PyMoDAQ’s Days: Lyon 20/22 October 2024

### ISSUE THREAD

**Issue by paugier** [PyMoDAQ/PyMoDAQ#311]
In http://pymodaq.cnrs.fr the link for Third edition of the PyMoDAQ’s Days: Lyon 20/22 October 2024 is https://pymodaq-jt2022.sciencesconf.org/

I'd like to participate but I cannot find the correct link.

Note: I'm Pierre Augier, CNRS researcher at LEGI (Grenoble) and creator/maintainer of [Fluiddyn](https://fluiddyn.readthedocs.io), a Python software suite to study fluid dynamics. We have a Python package to control experiments (fluidlab), which is used in particular for experiments in the Coriolis platform. I didn't work recently on Fluidlab but I think it contains useful code (in particular https://fluiddyn.readthedocs.io/projects/fluidlab/en/latest/generated/fluidlab.instruments.html). Anyway, I would be interested to see how we could use PyMoDAQ at LEGI (instead of Labview, which is still dominant here) and if things in Fluidlab could be useful for PyMoDAQ.

**Comment by seb5g** [comment]
Indeed the new link is: https://pymodaq-days.sciencesconf.org
I'll change it immediately! Thanks for letting me know!

It's very interesting, do you think you could propose a talk to present fluidlab? Then we'll be able to see how it can interact with pymodaq! Thx

**Comment by seb5g** [comment]
I would advise to register on the pymodaq mailing list to have all up to date info:
https://listes.services.cnrs.fr/wws/subscribe/pymodaq
