### ISSUE TITLE
DeSerializer.object_deserialization does not work

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/PyMoDAQ#320]
In #318 I noticed, that `Deserializer().object_deserialization()` does fail, while `Deserializer().dwa_deserialization()` works.

I expected `object_deserialization` to be a one-for-all method to deserialize anything (similar to `to_bytes`).

I figured out, why it fails:
https://github.com/PyMoDAQ/PyMoDAQ/blob/9244938e4292b5d06aa02e26b07947fcba6a7ccb/src/pymodaq/utils/tcp_ip/serializer.py#L620-L622

The second line (L621) reads the type, but reading already consumes the bytes from the strings.
Later on the called `deserialization` methods try to read the type again, which fails, as the type has been read and the corresponding bytes are not accessible anymore.

In #318 I propose a fix:
~~~python
    def object_deserialization(self, manual=False):
        """Deserialize an object.

        If you call it manually, you have to set manual to True.
        """
        obj_type = self.string_deserialization()
        hand_over = obj_type if manual else None
        elt = None
        if obj_type == 'scalar':
            elt = self.scalar_deserialization()
        elif obj_type == 'string':
            elt = self.string_deserialization()
        elif obj_type == 'array':
            elt = self.ndarray_deserialization()
        elif obj_type in ('dwa', "DataActuator"):
            elt = self.dwa_deserialization(obj_type=hand_over)
        elif obj_type == "DataToExport":
            elt = self.dte_deserialization(obj_type=hand_over)

    def dte_deserialization(self, obj_type: Optional[str] = None) -> DataToExport:
        """Convert bytes into a DataToExport object

        Convert the first bytes into a DataToExport reading first information about the underlying data

        Returns
        -------
        DataToExport: the decoded DataToExport
        """
        class_name = self.string_deserialization() if obj_type is None else obj_type
~~~

Here, the read obj_type is given to the deserialization method, which does not read the type again.
However, in order to not break code, this possibility is optional and disabled per default.

**Comment by seb5g** [comment]
I just looked at the tests because I thought I tested all cases but in fact the object_deserialiation is not tested hence the error you found. Did you add the tests for that?

**Comment by BenediktBurger** [comment]
Yes, I added the tests in order to figure out, what is wrong (and to test my solution).

**Comment by seb5g** [comment]
cool that sounds like a good patch! Wouldn't it be better to do a specific PR for this rather than including it into the pyleco current PR #318

**Comment by BenediktBurger** [comment]
> Wouldn't it be better to do a specific PR for this rather than including it into the pyleco current PR https://github.com/PyMoDAQ/PyMoDAQ/pull/318

Yes, therefore I created this issue. The PR only contains the needed code to work (data with axes / data to export)

What is the expected behavior of `object_deserialization`: Should it always give the detected version to the other methods or not?
The dte_deserialization calls it as well, therefore it must have worked for these cases, but not for mine.

I ask, in order to clarify, how to define that method and its parameters.

**Comment by seb5g** [comment]
Yeah looking into it, we should clarify:

- when serialized object type is known (for instance we expect scalar, string...) then just using their corresponding deserializer is ok
- object_deserialization is meant for converting back advanced objects (dwa and dte) which contains various other advanced objects (axes, dwa, ...) so for these (dwa and dte) it is mandatory to send first the type of each objects they contains in order to be recreated at the deserialization step

I'll work on this this morning!

**Comment by seb5g** [comment]
Ok I think I misled you. Our programs should be self aware of what type of object is to be expected. For instance a data_ready signal will convey a dte hence you should use a dte_deserialization method. The same applies for other objects. the method  _object_deserialization_ is only meant to be used within dte_deserialization od dwa_deserailization

Does that solves your issues? If yes I will add some docstrings and tests for that (and maybe make the _object_deserialization_ a private method)

**Comment by seb5g** [comment]
See #324

**Comment by BenediktBurger** [comment]
My goal was, to serialize all pymodaq objects (Axis, DataWithAxis, DataToExport, DataActuator... even the Parameter) to bytes and then to return it to the pymodaq object again without knowing, what to expect.
That makes the LECO transfer simple and transparent: A ThreadSignal is turned to JSON+Bytes, sent via LECO, later recreated and an appropriate signal emitted. The LECO transfer does not need to know, what the content is and what to expect.

As these pymodaq objects contain their name in the serialized bytes string, it is possible.
Maybe we could add a `complex_object_deserialization`, which can deserialize all these pymodaq objects.

**Comment by seb5g** [comment]
> Maybe we could add a `complex_object_deserialization`, which can deserialize all these pymodaq objects.

In that case, yes we should do that and also add the symmetric `complex_object_serialization` that will always add first the type of the serialized object (this could also be the current `Serializer.type_and_object_serialization` method where we could add some other types as needed)

I guess it is more informative to name those:

- `Serializer.type_and_object_serialization`
- `Deserializer.type_and_object_deserialization`

**Comment by seb5g** [comment]
PR #326 should close your issue

**Comment by BenediktBurger** [comment]
Thanks.
