### ISSUE TITLE
Feature request: (De)Serialize Parameter

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/PyMoDAQ#325]
For the pyleco transfer of information, it would be good, if there were a simple way to serialize and deserialize a parameter.
Optimally, it would be part of the serializer to have a single point for object->bytes and bytes->object.

Related to #320 , #318

**Comment by seb5g** [comment]
All pymodaq Parameter objects can already be serialized into xml string see :
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/eba9750e-00f2-44c5-bf3c-ee14326e87d1)

it is this string that is stored in the hdf5 attributes

this means that you can transfer the Parameter objects as a "string". We could make it transparent by including the Parameter type in the Serializer/Deserializer objects as discussed in #320 . if you agree I'll implement that

**Comment by BenediktBurger** [comment]
>  if you agree I'll implement that

I agree, as you know better what is necessary.

> serialized into xml string see

My point was to make it simple to use. Right now it is not clear, which method to use and, whether that result will contain all the information.
For example the path of a parameter is also relevant, but not part of the Parameter (or is it?).

**Comment by seb5g** [comment]
hello PR #326 should close this issue

**Comment by BenediktBurger** [comment]
Thanks, closed in that PR
