### ISSUE TITLE
Issue due to error_arrays when loading an Axis from h5 with DataSaverLoader

### ISSUE THREAD

**Issue by sq-lumin** [PyMoDAQ/PyMoDAQ#332]
Error when selecting an Axis in the h5browser (and probably when loading one directly from a DataSaverLoader instance ?): 

> 
> 2024-06-19 18:18:50,117 - pymodaq.browsing - ERROR - local variable 'error_arrays' referenced before assignment
> Traceback (most recent call last):
>   File ".\PyMoDAQ\src\pymodaq\utils\h5modules\browsing.py", line 530, in show_h5_data
>     data_with_axes = self.data_loader.load_data(node, with_bkg=with_bkg, load_all=plot_all)
>   File ".\PyMoDAQ\src\pymodaq\utils\h5modules\data_saving.py", line 1081, in load_data
>     data = self._data_loader.load_data(where, with_bkg=with_bkg, load_all=load_all)
>   File ".\PyMoDAQ\src\pymodaq\utils\h5modules\data_saving.py", line 474, in load_data
>     errors=error_arrays,
> UnboundLocalError: local variable 'error_arrays' referenced before assignment

Proposed fix : set 'error_arrays' to None when an axis is loaded with a DataSaverLoader
(I can pull request if the fix is accepted)

in pymodaq\utils\h5modules\data_saving.py:

```
class DataSaverLoader(DataManagement):
    ....
    def load_data(self, where, with_bkg=False, load_all=False) -> DataWithAxes:
        ....
        if 'axis' in self.data_type.name:
            ndarrays = [squeeze(data_node.read()) for data_node in data_nodes]
            axes = [Axis(label=data_node.attrs['label'], units=data_node.attrs['units'],
                         data=np.linspace(0, ndarrays[0].size-1, ndarrays[0].size-1))]
            error_arrays = None    # PROPOSED FIX
        else:
            ...
```

NOTE : should Axis objects be able to have errorbars ? then this fix would not be sufficient

**Comment by seb5g** [comment]
that will certainly fix the issue, please do it and I will review if tests are needed. Please do a PR including both #332  and #333
