### ISSUE TITLE
Issue due to Axis objects not having a timestamp when loading from a DataSaverLoader

### ISSUE THREAD

**Issue by sq-lumin** [PyMoDAQ/PyMoDAQ#333]
Issue due to Axis objects not having a timestamp when loading from a DataSaverLoader:

> 2024-06-19 18:31:49,718 - pymodaq.browsing - ERROR - "Attribute ('timestamp') does not exist in node '/RawData/Scan000/Detector000/Data1D/CH00/Axis00'"
> Traceback (most recent call last):
>   File "C:\Users\sebqu\miniforge3\envs\PyMoDAQ_dev\lib\site-packages\tables\attributeset.py", line 546, in __getitem__
>     return self.__getattr__(name)
>   File "C:\Users\sebqu\miniforge3\envs\PyMoDAQ_dev\lib\site-packages\tables\attributeset.py", line 283, in __getattr__
>     raise AttributeError(f"Attribute {name!r} does not exist "
> AttributeError: Attribute 'timestamp' does not exist in node: '/RawData/Scan000/Detector000/Data1D/CH00/Axis00'

Proposed fix: adding 'if' block checking the data type before setting it's timestamp:
(I can pull request along with  #332 if the fixes are accepted)

in pymodaq\utils\h5modules\data_saving.py:

```
class DataSaverLoader(DataManagement):
    ....
    def load_data(self, where, with_bkg=False, load_all=False) -> DataWithAxes:
        ....
        if 'axis' not in self.data_type.name:    # PROPOSED FIX
            data.timestamp = data_node.attrs['timestamp']
        return data
```

**Comment by seb5g** [comment]
yes that will do, I was just about looking into this when I saw your issue!!

**Comment by seb5g** [comment]
before doing anything, I'll have to look at why no test were covering this. Are you familiar with pytest?

**Comment by seb5g** [comment]
please do it and I will review if tests are needed. Please do a PR including both https://github.com/PyMoDAQ/PyMoDAQ/issues/332 and https://github.com/PyMoDAQ/PyMoDAQ/issues/333

**Comment by sq-lumin** [comment]
> before doing anything, I'll have to look at why no test were covering this. Are you familiar with pytest?

Not yet 😕 sorry.
I did the PR #338, thank you for the review !

**Comment by seb5g** [comment]
I did a PR #341 to add the tests
