### ISSUE TITLE
Slot decorator typo  in dashboard.py line 1213

### ISSUE THREAD

**Issue by loicguilmard** [PyMoDAQ/PyMoDAQ#339]
line 1213 :

    Slot(bool)
    def stop_moves(self, overshoot):

I figure it's supposed to be @Slot(bool) ?
Seems to be present in dev branches too.

**Comment by seb5g** [comment]
we should actually remove this decorator as it is not mandatory but you're right. do you do a PR?

**Comment by loicguilmard** [comment]
sure. bugfix on 4.2.x or 4.3.x_dev ?
or may be you can choose after the PR ? (i am not that fluent with github)

**Comment by seb5g** [comment]
you have to create a branch based on one and then you can choose to which one do the PR. The easiest is to choose the same one for both. Here you can do it on 4.2.x and I'll cherry pick it for 4.3.x_dev
