### ISSUE TITLE
Crash of plugin manager while updating teh plugin list

### ISSUE THREAD

**Issue by jerlfan** [PyMoDAQ/PyMoDAQ#340]
When I launch the plugin manager from the dashboard or the terminal, I got the following message in the terminal and both dashboard and plugin_manager close.

QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

**Comment by seb5g** [comment]
Could you specify the version you're using for:

- python
- pymodaq
- plugin_manager

**Comment by seb5g** [comment]
For me it works with :
- python: 3.10.14
- pymodaq: 4.3.x (dev)
- plugin_manager (1.2.3)

**Comment by jerlfan** [comment]
not working for

- python: 3.10.14
- pymodaq: 4.2.3
- plugin_manager (1.2.3)

**Comment by seb5g** [comment]
it looks like not an issue related to pymodaq but os and Qt. What's your OS and version of :
pyqt5?
Qt5?
@quantumm  could you try this as well?
@rgeneaux could you try this as well?

**Comment by jerlfan** [comment]
OS version : Windows 10 pro
pyqt5 : 5.15.10
pyqt5-qt5 : 5.15.2

**Comment by jerlfan** [comment]
I confirm it doesn't work for me with 

- python: 3.10.14
- pymodaq: 4.3.x (dev)
- plugin_manager (1.2.3)

**Comment by seb5g** [comment]
> OS version : Windows 10 pro
> pyqt5 : 5.15.10
> pyqt5-qt5 : 5.15.2

I have all the same versions as you do...

**Comment by jerlfan** [comment]
I solved the problem but I don't understand. 
I have first checked the version of pymodaq via the dashboard (with pymodaq 4.2.3 and 4.3.x dev). 
Then I launched the plugin manager and it works. 

I still have the following in the terminal:

QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

**Comment by rgeneaux** [comment]
Hi, checked in two environments I had around
1) pymodaq==4.2.2, python==3.8.0, pymodaq-plugin-manager==**1.2.3** same pyqt5 as you guys
==> I get the same 'QTextCursor' warning in the terminal but things work.
NB: the log messages "Fetching metadata for package pymodaq-plugins-xxx" appear in the plugin manager window

2) pymodaq==4.3.x_dev, python==3.9.0, pymodaq-plugin-manager==**1.0.1** (I guess I always checkout from branches on pymodaq repo, which doesn't update the manager)
==> everything works, no error message. 
NB: the log messages "Fetching metadata for package pymodaq-plugins-xxx" appear in the terminal, not in the plugin manager window

then after upgrading to pymodaq-plugin-manager==**1.2.3**, the 'QTextCursor' thing appears, and the log messages are in the plugin manager window.
