### ISSUE TITLE
Unable to install plugin in editor mode with pip

### ISSUE THREAD

**Issue by martinluttmann** [PyMoDAQ/PyMoDAQ#352]
Hello,

I am trying to import the repository pymodaq_plugins_template in order to write a new plugin. I forked the repository on my github, and cloned it locally on my computer. However, when I "cd" in the folder in the pycharm terminal and enter "pip install -e .", the following error message appears

![error](https://github.com/PyMoDAQ/PyMoDAQ/assets/44998370/b7736d7a-4581-4dd3-9d35-7056ffe8925a)

In particular, it ends with : "No matching distribution found for pymodaq>=4.3.0". The same problem occurs with other plugins repositories.

I never had this problem before, and I already wrote 2 plugins using the same method, as described in pymodaq's documentation. I do not know if it is a problem with pip or with pymodaq. I am using an environment with python 3.11 .

Thanks in advance!

**Comment by rgeneaux** [comment]
Indeed it looks like the template has pymodaq>=4.3.0 as requirement even though 4.3.0 as not yet been released as a stable version.

For your immediate needs, you can install the development version of pymodaq 4.3.0 from github (it works, no worries there!) like so:
`pip install git+https://github.com/PyMoDAQ/PyMoDAQ@4.3.x_dev`
Then you `pip install -e .` will work

I'll let @seb5g decide whether to release 4.3.0, or to change the requirements on the plugin template ;)

**Comment by seb5g** [comment]
The most to date plugin template use some functionalities I recently added
in 4.3.0. so either you use the dev version for the moment or change the
requirement in the template with the risk to have to patch the new
functionality. I would suggest first option as I will soon release the 4.3.0

**Comment by martinluttmann** [comment]
Thank you for your answers! I used the 1st option, it is working now.
