### ISSUE TITLE
List of compatible instruments not displayed correctly

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#365]
Hi!

There is a problem with the README of the [Plugin Manager repository](https://github.com/PyMoDAQ/pymodaq_plugin_manager/), the end of the table is not displayed correctly.

**Comment by seb5g** [comment]
Coul you pinpoint which package is causing the issue. It is probably an error in the readme layout of a given plugin

**Comment by quantumm** [comment]
This has been solved. I close the issue.
