### ISSUE TITLE
MIssing scrolling bar in "Do Scans" extension

### ISSUE THREAD

**Issue by BotiKepi** [PyMoDAQ/PyMoDAQ#368]
Changing parameters can be tricky in "Scanner settings > scanner_settings" section of Scan extension.

This happens especially whenever *Scan type* is *sequential*  or *tabular*, where several lines may be inserted.
In such case, a **scrolling bar is missing** to reach all the lines (depending on probably the size of the window).

Tested with pymodaq 4.3.0 under Windows OS.

**Comment by malik-irain** [comment]
Could you provide a screenshot, because they seem to be here on pymodaq 5.0.x_dev with linux?

**Comment by malik-irain** [comment]
It works on version 5.0.x_dev but not on 4.4.7 and it doesn't come from the dark style.

**Comment by seb5g** [comment]
could not find obvious way to solve it and could not remember doing it on v5 compared to v4... As it happens only on small screens and is fixed on v5 I would propose to close this issue to focus on more urgent thing
