### ISSUE TITLE
greetings from Wisconsin USA

### ISSUE THREAD

**Issue by untzag** [PyMoDAQ/PyMoDAQ#37]
Hello :wave:, I hope you don't mind me opening this issue. My colleague @ksunden and I recently found your project. We were immediately struck by the similarities between your project and our own efforts. I'll try to introduce what we're working on a bit here.

@ksunden and I are building [yaq](https://yaq.fyi/), a project which attempts to simplify the process of communicating with scientific instrumentation. yaq is a collection of daemons (microservices), each enabling communication with a particular kind of instrumentation. Clients connect with these daemons via TCP (local or remote). Development happens here: https://gitlab.com/yaq

Importantly, we are building yaq to work with a variety of different clients. yaq itself focuses on just hardware communication. I'm currently most excited about integration with [the Bluesky Project](https://blueskyproject.io/), a growing ecosystem of tooling that promises to simplify hardware orchestration, data collection, and GUI creation. Bluesky has historically focused on [EPICS](https://epics-controls.org/), but they have designed their ecosystem to easily plug into any Python-based hardware control system. We integrate via a little shim package [yaqc-bluesky](https://github.com/bluesky/yaqc-bluesky). It's not perfect, but it's great to use Bluesky where possible since they have so many more developers and much more maturity than others I've come across.

I imagine from this introduction you can see how much overlap there is between our projects. I'm writing to connect with the hope that we might build together somehow. I've got a few ideas... but what do you think?

**Comment by seb5g** [comment]
Hello There. Thanks for getting in touch. I had a detailed look into yaq today and found it quite promising. I would like to propose to build a generic PyMoDAQ plugin to show how to include the communication with yaq daemons (using the Client object obviously). I already started with the fake daemon but:

- I was looking in a way to check from within python how to get a list of installed daemons. As they are (mostly) python packages I was trying to discover them using the ``pkg_resources`` and its iter_entry_points method. But it does'nt seem any "plugin" entry points are defined (it's how I do it with pymodaq). What do you advice to use to discover them except from parsing the command line.

- Then, how to access the list/type of user parameters for a given daemon (also from within python if possible)

Cheers
Seb

**Comment by seb5g** [comment]
By the way, may I ask where you heard about PyMoDAQ?

**Comment by untzag** [comment]
Thanks for your response @seb5g ---I like your idea of building a plugin to consume yaq daemons in PyMoDAQ. Hopefully then we can wrap around and start using some of your client side / GUI tools rather than inventing our own :smile: 

Unfortunately I don't have an answer for how to automatically discover all the yaq daemons installed on a given machine. It's just not something we've needed yet. That said it shouldn't be hard and I'm happy to add it. I've got a plan that I think will work for PyMoDAQ and also be easily accessible to other tools down the road---see https://gitlab.com/yaq/yaqd-control/-/issues/19

For accessing daemon parameters, I would just use [yaqc](https://gitlab.com/yaq/yaq-python/-/tree/master/yaqc). This very small package that simply connects to a daemon, reads the complete protocol, and dynamically creates a client object based on what it finds. The magic happens [here](https://gitlab.com/yaq/yaq-python/-/blob/master/yaqc/yaqc/_client.py#L60-76).
```python
>>> import yaqc
>>> client = yaqc.Client(38999)  # happens to be a fake-triggered-sensor daemon
>>> client.traits  # traits might be helpful to build your interface
['is-daemon', 'has-measure-trigger', 'is-sensor']
>>> client.get_measured()  # all the methods work as expected
{'random_walk': 0.14179018749612823, 'measurement_id': 0.0}
>>> client._protocol  # full protocol as python dict
```

@ksunden was the one to stumble across your package, so I'll let him give any details. I think the short story is that he was searching for "python instrumentation" or something similar on GitHub and you were one of the top results.

**Comment by seb5g** [comment]
Did you make progress is this daemon discovery?

**Comment by untzag** [comment]
I did! You should now be able to call `yaqd list --format json`. On my machine the following function:

```python
import subprocess
import json

def get_yaq_daemons():
    completed_process = subprocess.run(["yaqd", "list", "--format", "json"], check=True, capture_output=True)
    return json.loads(completed_process.stdout.decode())
```

Gives me the following dictionary:

```json
{
  "127.0.0.1:38999": {
    "host": "127.0.0.1",
    "port": 38999,
    "kind": "fake-triggered-sensor",
    "name": "daq",
    "config_filepath": "/root/.config/yaqd/fake-triggered-sensor/config.toml",
    "make": null,
    "model": null,
    "serial": null
  },
  "127.0.0.1:39876": {
    "host": "127.0.0.1",
    "port": 39876,
    "kind": "fake-continuous-hardware",
    "name": "wm",
    "config_filepath": "/root/.config/yaqd/fake-continuous-hardware/config.toml",
    "make": null,
    "model": null,
    "serial": null
  },
  "127.0.0.1:38500": {
    "host": "127.0.0.1",
    "port": 38500,
    "kind": "fake-continuous-hardware",
    "name": "d0",
    "config_filepath": "/root/.config/yaqd/fake-continuous-hardware/config.toml",
    "make": null,
    "model": null,
    "serial": null
  },
  "127.0.0.1:39000": {
    "host": "127.0.0.1",
    "port": 39000,
    "kind": "seabreeze",
    "name": "usb2000",
    "config_filepath": "/home/blaise/.config/yaqd/seabreeze/config.toml",
    "make": null,
    "model": null,
    "serial": null
  },
  "127.0.0.1:38000": {
    "host": "127.0.0.1",
    "port": 38000,
    "kind": "fake-spectrometer",
    "name": "myfake",
    "config_filepath": "/home/blaise/.config/yaqd/fake-spectrometer/config.toml",
    "make": null,
    "model": null,
    "serial": null
  }
}
```

I hope this works for you. Let me know I'd be happy to help trying and making some tooling to get yaq working with pymodaq.
