### ISSUE TITLE
PySide6 and Pyqt6 compatibility

### ISSUE THREAD

**Issue by seb5g** [PyMoDAQ/PyMoDAQ#415]
It is time to work on that!

**Comment by seb5g** [comment]
https://github.com/PyMoDAQ/pymodaq_gui/pull/9 has fixed this (tested with PyQt6)

still test with PySiDE 6

**Comment by seb5g** [comment]
@malik-irain could you add a test using pyside6 in the test suite?

**Comment by malik-irain** [comment]
It's done in PR #463
