### ISSUE TITLE
update docs to match the pymodaq5 submodule splitting (and a missing picture)

### ISSUE THREAD

**Issue by loicguilmard** [PyMoDAQ/PyMoDAQ#420]
Reference to : AxisBase, DataWithAxis and DataFromPlugins are broken in the documentation :
for instance :
DataFromPlugins is still in pymodaq.utils.data  not in pymodaq_data.data 
but i am not sure what to do, change the doc reference back to pymodaq.utils or move the class definition in pymodaq_data ?

It also seems a picture is missing in PyMoDAQ\docs\src\data_management\plotting_data_objects.rst line 364
ERROR: Error in "image" directive:

**Comment by loicguilmard** [comment]
May be duplicate the documentation for the 2 versions 4.x and 5.x ?

**Comment by seb5g** [comment]
What we could do is:

* do the main documentation on pymodaq
*  do the API documentation on each package where it's relevant. 

So for instance we keep the general dicussion about DataManagement on pymodaq but move the API of its objects to where there are defined, that is in pymodaq_data

What do you think?

**Comment by loicguilmard** [comment]
For the packages, it's perfect.
For the library reference on the website pymodaq.cnrs.fr, may be it would be nice to have the 2 versions next to each other for now. So the users/dev can still debug/understand their 4.x pymodaq setups.

For the DataManagement documentation, you want to remove the import in the exemple and point to the module documentation ? How confusing would it be for 4.x users ?

What about the tutorials ? Shall we tag them with version as the library reference ?

**Comment by seb5g** [comment]
Hello both versions of the documentation is available at the moment: 
![image](https://github.com/user-attachments/assets/091fc279-70d2-4bea-b24d-78121913e1fd)

**Comment by loicguilmard** [comment]
My bad.
Then it's just a correction of the exemples of the 5.0.X_dev data documentation from pymodaq.utils.data to pymodaq_data.data ?
Where do i need to look to get the version selection or select the version i am updating ? I don't have this selection on my local make html.

**Comment by seb5g** [comment]
the documentation are build from the source directly on the readthedocs project. Both branches 4.4.x and 5.0.x_dev can trigger the compilation with their respective target on the doc. So if you want to change the 5.0.x_dev doc, change this branch and commit (PR) and inversely

**Comment by loicguilmard** [comment]
Those have been corrected and all other the submodule/splitting documentation issues are enhancement, at least to me :)
