### ISSUE TITLE
Crazy DAQ_Move Mock since version 4.3 on Ubuntu

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#424]
Hi,

I made a fresh environment with python=3.11 and pymodaq=4.4 on Ubuntu.
Running a daq_move mock, the behavior was completely crazy: displaying units like "mµm" inside the green/red boxes and clicking any button was not doing the expected behavior.

I went back to pymodaq=4.3: same.

I went back to pymodaq=4.2: the daq_move mock is cured and works perfectly fine!

**Comment by seb5g** [comment]
I like crazy actuators :-)

**Comment by quantumm** [comment]
I like this prompt response ;)

It works!
