### ISSUE TITLE
pymodaq4 extension loading pymodaq_utils ?

### ISSUE THREAD

**Issue by loicguilmard** [PyMoDAQ/PyMoDAQ#445]
I am not sure it's a bug i didn't verify it.
But in  last branches 4.x.x  in file pymodaq/extensions/pid/daq_move_PID.py :
from pymodaq_utils.utils import ThreadCommand

**Expected behavior**
I figure it should be from pymodaq.utils.daq_utils import ThreadCommand

**Additional context**
If i am not mistaken, do you want me to PR ?

**Comment by loicguilmard** [comment]
In utils/data.py : 
import pymodaq

doesn't seem to be used anywhere

**Comment by seb5g** [comment]
I removed the folder daq_utils since I moved to v5. ThreadCommand is in pymodaq_utils.utils

**Comment by seb5g** [comment]
> In utils/data.py : import pymodaq
> 
> doesn't seem to be used anywhere

don't see where this import is?

**Comment by loicguilmard** [comment]
Both path surprises are in  pymodaq branch 4.4.X : 
src/pymodaq/utils/data.py line 23 => import pymodaq
pymodaq/extensions/pid/daq_move_PID.py shouldn't use pymodaq_utils because it's branche 4.4.x i thought pymodaq_utils appeared in 5.x

**Comment by seb5g** [comment]
> Both path surprises are in pymodaq branch 4.4.X : src/pymodaq/utils/data.py line 23 => import pymodaq pymodaq/extensions/pid/daq_move_PID.py shouldn't use pymodaq_utils because it's branche 4.4.x i thought pymodaq_utils appeared in 5.x

you're correct for both

**Comment by loicguilmard** [comment]
should i submit a PR for that or you'll include it in next wagon ?

**Comment by seb5g** [comment]
do it please!

Sébastien Weber

*Référent Organisation AbsoluRaid*
***@***.*** ***@***.***>*
*https://absoluraid.fr/ <https://absoluraid.fr/>*


Le lun. 18 nov. 2024 à 14:08, loicguilmard ***@***.***> a
écrit :
