### ISSUE TITLE
pip fails to install pymodaq 5 in editable mode

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#460]
**Describe the bug**
pip fails to install pymodaq 5 in editable mode.

**To Reproduce**
1. Clone the branch 5.0.x_dev (with pycharm. I do not know for now if it matters)
2. Create a dedicated environment and activate
3. pip install -e "path to the root of the pymodaq5 folder"

**Expected behavior**
Install pymodaq5 in the environment.

**Error**
`INFO: pip is looking at multiple versions of pymodaq-plugins-mock to determine which version is compatible with other requirements. This could take a while.
Collecting pymodaq-plugins-mock>=5.0.5 (from pymodaq==3.5.7.dev1684+g1f5749bf)
  Using cached pymodaq_plugins_mock-5.0.9-py3-none-any.whl.metadata (5.0 kB)
  Using cached pymodaq_plugins_mock-5.0.8-py3-none-any.whl.metadata (5.0 kB)
  Using cached pymodaq_plugins_mock-5.0.7-py3-none-any.whl.metadata (5.0 kB)
  Using cached pymodaq_plugins_mock-5.0.6-py3-none-any.whl.metadata (5.0 kB)
  Using cached pymodaq_plugins_mock-5.0.5-py3-none-any.whl.metadata (5.0 kB)
ERROR: Cannot install pymodaq and pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.10 depends on pymodaq>=5.0.0
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.9 depends on pymodaq>=5.0.0
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.8 depends on pymodaq>=5.0.0
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.7 depends on pymodaq>=5.0.0
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.6 depends on pymodaq>=5.0.0
    The user requested pymodaq 3.5.7.dev1684+g1f5749bf (from /home/quantumm/PycharmProjects/PyMoDAQ5)
    pymodaq-plugins-mock 5.0.5 depends on pymodaq>=5.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict`

**Desktop (please complete the following information):**
 - OS: Xubuntu 22.04
 - Browser: Firefox

**Additional context**
I do not know why it is talking about pymodaq 3.5.7 in the error.
I thought it was a cache problem, but an install with "no-cache" option of pip produced the same result.
An install directly from source (no editable mode : pip install git+https://github.com/PyMoDAQ/PyMoDAQ.git@5.0.x_dev) is working fine.

**Comment by quantumm** [comment]
I just checked that the error is not due to Pycharm.
I can reproduce it using git directly.

**Comment by seb5g** [comment]
This 3.5.7 is weird and probably at the heart of this issue... The versioning is done using git tags and we've seen similar issues recently. @malik-irain is on something similar and will look at it

**Comment by malik-irain** [comment]
From what I see, it seems you have pymodaq 3.5.7 already installed. It could be because you're using an existing environment, it can happen even if you create a new environment if its the same name as an already existing one.

You can maybe try changing the name of the environment you create

Anyway, could you provide the output of `pip list` command in this problematic environment?

**Comment by quantumm** [comment]
Hi,

I created a new environment with a name I never used. I am quite sure about that.

It could be that I had the 3.5.7 version installed at some point on this machine. Could it be something related to old config files that are still stored somewhere on the computer?

Anyway, here is the output of `pip list`:

(pmd5_doc_2) quantumm@ThinkPadX201:~/local_repository/pymodaq5_doc_2$ pip list
Package    Version
---------- -------
pip        24.3.1
setuptools 75.6.0
wheel      0.45.1

And the output of `mamba list`:

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
python                    3.11.10         hc5c86c4_3_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge

Thanks for your help!

**Comment by malik-irain** [comment]
> Hi,
> 
> I created a new environment with a name I never used. I am quite sure about that.
> 
> It could be that I had the 3.5.7 version installed at some point on this machine. Could it be something related to old config files that are still stored somewhere on the computer?

I don't think so, if that were the case it wouldn't fail to install in a fresh environment

Could you now go to the root of the pymodaq5 folder, activate the environment, install hatch with pip (`pip install hatch`) and run `hatch version`. 

If it return 3.5.7.dev-xxx... it's a "problem" with github default forks configuration: it only takes one branch and don't track all the tags, which are actually used by PyMoDAQ to determine the version. If so, run:

```
git remote add upstream https://github.com/PyMoDAQ/PyMoDAQ 
git fetch upstream --tags
git remote remove upstream
```

It will add https://github.com/PyMoDAQ/PyMoDAQ  as a remote repo, then get the tags from it and finally remove the the repo (so you don't push by accident). 

After that you should be able to continue the install (`pip install -e <pymodaq5 path>`)

I may be necessary to run it again in the future (for v6 you still have time !) as the tags will still not be automatically updated

**Comment by quantumm** [comment]
`hatch version` actually returned 3.5.7.dev1684+g1f5749bf.

I followed blindly your instructions (I don't understand the tag thing ;) ).

After that `hatch version` returned 5.0.1.dev154+g1f5749bf

I run again the editable installation and it worked ;)

Thank you so much for your help!

**Comment by manvrard** [comment]
@malik-irain could you investigate what would be required to solve this as many people would face it... By the way, i remembered that the "default" version number is for people who don't have git installed (or the computer don't find it in case of user specific installation). So we need to specify it for all pymo packages

**Comment by ederag** [comment]
This may happen because when forking through the github interface,
the default is to clone only one branch:

![Image](https://github.com/user-attachments/assets/19270aa8-3c79-4b59-b621-98b7c267d2f4)

The doc should probably indicate to uncheck this box ?

**Comment by seb5g** [comment]
good idea, would you like to propose a PR to include this change in the doc?
