### ISSUE TITLE
[BUG] running plugin v4 with pymodaq v5

### ISSUE THREAD

**Issue by loicguilmard** [PyMoDAQ/PyMoDAQ#475]
### Describe the bug

running pymodaq v5 from git, the nidaq detector doesn't appear

### Expected Behavior

You can run plugin with the v4 with pymodaq v5.
Parameter, pymodaq_ptypes, registerParameterType, GroupParameter could still be importable with the old path : from pymodaq.utils.parameter

### Steps To Reproduce

install pymodaq v5 and pymodaq_daqmx
run the dashboard
you can't add the NIDAQ detector

### Reference(s)

```markdown
pymodaq_plugins_daqmx.daq_move_plugins/NIDAQmx is available
but
from pymodaq.utils.parameter import Parameter
from pymodaq.utils.parameter.pymodaq_ptypes import registerParameterType, GroupParameter
those moved to pymodaq_gui.
```

### Environment

```markdown
- OS: windows 11
- Pymodaq: 5.0.1dev
- python env: 
pyqt5
nidaqmx
```

### Additional context

If i changed pymodaq.utils to pymodaq_gui, it works.
If it is the intended behavoir, just close the issue :)

**Comment by seb5g** [comment]
@loicguilmard could you recheck if this solves your plugin issues?

**Comment by loicguilmard** [comment]
@seb5g it didn't work.
i used sysmodules["pymodaq.utils.parameter.pymodaq_ptypes"] = pymodaq_ptypes
tested it and it works.
check this [PR](https://github.com/PyMoDAQ/PyMoDAQ/pull/495)

**Comment by seb5g** [comment]
ok I accepted your PR!
