### ISSUE TITLE
Testing PID extension

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#72]
Hi!

I had a look at the video about the [PID extension](https://www.youtube.com/watch?v=u8ifY4WqQEA) and tried to test it but i faced several issues:

1. I do not understand how I am supposed to deal with the installation of the extension. I see there is a pymodaq_pid repository but it is not a PyPI package (I installed pymodaq_pid_models).
2. I think there is a mistake in the load_pid_module method in dashboard.py l.196. self.pid_window should probably be win.
3. In the import of dashboard.py DAQ_PID is taken from pid_controller defined in the subfolder pid of pymodaq. I guess it should take it from the pymodaq_pid once it has been installed no?

I am a bit lost… :)
Thanks a lot!

**Comment by seb5g** [comment]
could you update your issue or close it?
