### ISSUE TITLE
Adding a new plugin to the project

### ISSUE THREAD

**Issue by LMSC-NTappy** [PyMoDAQ/PyMoDAQ#74]
Hi @seb5g,

just finished an extension for the support of a new microscopy stage.

It's available over there: https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena

If you don't mind giving me a few instructions I'd be happy to add it to the plugin manager

Best Regards

Nicolas

**Comment by rgeneaux** [comment]
Hi Nicolas,

Basically you need to publish your package on pypi, and the plugin manager will see it directly.

Here's how I do it:
1. First you need to have an account on pypi, and add the login info to Github as a "secret" (secrets.PYPI_USERNAME and secrets.PYPI_PASSWORD). They need to be available either to your entire Github account, or just to your repository. If you need help for this let me know. 

2. Release your package:
- First set your package version number in the [VERSION](https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena/blob/master/src/pymodaq_plugins_piezosystemjena/VERSION) file. It looks like Seb is going with "0.1.0" for first releases of working plugins. 
- Then in github, create a [Release](https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena/releases) (right side of the main screen of your repository), with the same Version number as the one you just set.
- This will trigger the nice github workflow that Seb made and included in the plugin template, [python-publish.yml](https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena/tree/master/.github/workflows/python-publish.yml)
- If the login info is correct, this will upload the package to pypi. You can follow the publish script in [Actions](https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena/actions). You'll see if the run was successful or if it encountered issues.

3. Every Sunday at 12:00, pymodaq plugin manager will look for any new or updated pypi package named "pymodaq-plugins-xxxx". This should add your plugin to everyone's list (you can verify on your computer, or the readme of https://github.com/CEMES-CNRS/pymodaq_plugin_manager)

Let me know if you're having trouble!
Romain

**Comment by LMSC-NTappy** [comment]
Thank you very much for these informations!

The new version of Pylablib is out so I'll try next week when I am back from conference

Keeping this issue opened until then.

**Comment by seb5g** [comment]
What Romain wrote is the right procedure !

**Comment by LMSC-NTappy** [comment]
Just managed to package the plugin as well as an other one.

If the plugin manager finds them correctly in the pypi jungle tomorrow, I guess we'll be able to close this issue :)

Thanks for the help @rgeneaux and @seb5g . Worked just right so far!

For posterity, in case someone reads these lines in search for infos:
-the secrets are added in the repository directly and must be named PYPI_USERNAME and PYPI_PASSWORD directly when added. See for details https://docs.github.com/en/actions/security-guides/encrypted-secrets
-The version number during release is actually set in the "tag" field.

**Comment by LMSC-NTappy** [comment]
After taking a look today, including in a fresh PyMoDAQ installation, it seems that the plugin_manager is unable to find my plug-ins :'/

They correctly appear on the readme of the plugin manager and redirect to the right pip page. 

Care to take a look? I probably am doing something wrong like not having the right name or stg.

Cheers

Nico

**Comment by rgeneaux** [comment]
I read that the package index (https://pypi.org/simple/) oftentimes has long delays to add new packages (or new versions). Indeed your package is not present in the index yet. 
But your plugin is on pypi and I could install it just fine from pip install. So maybe let's just wait a few days :)

**Comment by LMSC-NTappy** [comment]
Thanks for the reply!

Let's just wait then :)

**Comment by LMSC-NTappy** [comment]
And indeed this morning it's good and now appears.

CLosing this now, many thanks for your help!

N

**Comment by rgeneaux** [comment]
Cool! 
another thing: your latest release (0.1.1) didn't get published to pypi (see here https://pypi.org/project/pymodaq-plugins-piezosystemjena/#history)
this is because your [VERSION](https://github.com/LMSC-NTappy/pymodaq_plugins_piezosystemjena/tree/master/src/pymodaq_plugins_piezosystemjena/VERSION) file still says 0.1.0

You can just delete your 0.1.1 release, commit the VERSION, and re-release to trigger the publish action.

@seb5g I guess we should write everything from this issue into the documentation? Currently it's a bit light on the plugin publishing part. I tried to add it to the PyMoDAQ Roadmap but I do'nt have write access yet :-)

**Comment by LMSC-NTappy** [comment]
Damit...

I am updating this now and I will re-release later this week. People in my lab will be using the plug-in so I'll wait to make sure nothing comes up

Thanks for the heads up!

**Comment by seb5g** [comment]
I gave you both access to the project on the new PyMoDAQ organisation (changing name went smoothly). You can write things in the project and you could manage repository if needed or if you move your plugins in there!
